services:
  backend:
    build:
      context: ./backend  # Контекст сборки из папки backend в папке docker
      target: dev
    volumes:
      - ../backend:/app/  # Путь из текущей папки backend в контейнер /app/
      - ./backend/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    extra_hosts:
      - host.docker.internal:host-gateway
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on: [backend]
    links:
      - backend
    networks:
      - default
      - nginx
    volumes:
      - ../backend:/app/
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: ${BASE_DOMAIN}
      VIRTUAL_PATH: /api

  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6
    ports:
      - published: 80
        target: 80
    networks:
      - default
      - nginx
    volumes:
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  docs:
    image: swaggerapi/swagger-ui:v5.18.2
    networks:
      - default
      - nginx
    environment:
      SWAGGER_JSON_URL: /docs/openapi.yaml
      BASE_URL: /docs
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${BASE_DOMAIN}
      VIRTUAL_PATH: /docs
    volumes:
      - ../backend/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
    networks:
      - default
      - nginx
    environment:
      VIRTUAL_PORT: 5173
      VIRTUAL_HOST: ${BASE_DOMAIN}
      VIRTUAL_PATH: /

volumes:
  vhost:
  conf:
  html:
  certs:
  data:

networks:
  nginx:
    name: nginx
    driver: bridge
